# Use root/example as user/password credentials
version: '3.1'

services:

  mongo-dc:
    image: mongo:latest
    volumes:
      - /home/uly55e5/Projekte/ipb/datacite-db/data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: datacite
      MONGO_INITDB_ROOT_PASSWORD: datacite
    ports:
      - 27017:27017

  mongo-express-dc:
    image: mongo-express
    restart: always
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: datacite
      ME_CONFIG_MONGODB_ADMINPASSWORD: datacite
      ME_CONFIG_MONGODB_SERVER: mongo-dc